# Generated by Django 3.1 on 2021-09-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reference_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
