# Generated by Django 3.1 on 2021-09-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reference_code',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
