# Generated by Django 3.1 on 2021-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210907_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True, unique=True),
        ),
    ]
