# Generated by Django 3.1 on 2021-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211030_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_currency_awarded',
            field=models.BigIntegerField(default=0),
        ),
    ]
