# Generated by Django 3.1 on 2021-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_initial_currency_awarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='initial_currency_awarded',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
