# Generated by Django 3.1 on 2021-12-24 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0031_auto_20211002_0527'),
        ('accounts', '0015_auto_20211109_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCurrencyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_currency', models.BigIntegerField(blank=True, default=0, null=True)),
                ('lose_currency', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_history_round', to='misc.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
