# Generated by Django 3.1 on 2021-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usercurrencyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lose_currency',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='won_currency',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
