# Generated by Django 3.1 on 2021-03-16 08:21

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0002_auto_20210315_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tx',
            fields=[
                ('sent', models.IntegerField()),
                ('received', models.IntegerField()),
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
            },
        )
    ]
