# Generated by Django 3.1 on 2021-03-16 08:21

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        # ('misc', '0007_auto_20210614_0812')
        ('misc', '0031_auto_20211002_0527')
    ]

    operations = [
        migrations.RunSQL(f"create view casino_received as select date(created_at) date, sum(amount) received from misc_transaction where receiver_id = {settings.CASINO_USER_ID} and round_id IS NOT NULL group by date(created_at)", reverse_sql="drop view casino_received"),
        migrations.RunSQL(f"create view casino_sent as select date(created_at) date, sum(amount) sent from misc_transaction where sender_id = {settings.CASINO_USER_ID} and round_id IS NOT NULL group by date(created_at)", reverse_sql="drop view casino_sent"),
        migrations.RunSQL("create view analytics_tx as select coalesce(casino_sent.date ,casino_received.date) as date, casino_sent.sent, casino_received.received from casino_received full outer join casino_sent on casino_received.date = casino_sent.date", reverse_sql="drop view analytics_tx")
    ]