# Generated by Django 3.1 on 2021-12-24 14:40

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usercurrencyhistory'),
        ('analytics', '0002_tx_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSummary',
            fields=[
            ],
            options={
                'verbose_name': 'User Registration',
                'verbose_name_plural': 'User Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
