# Generated by Django 3.1 on 2021-03-15 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=5000)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gametable',
            old_name='game_table',
            new_name='game_table_type',
        ),
        migrations.AddField(
            model_name='gametable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gametablehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inapppurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='gametabletype',
            name='image',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='inapppurchase',
            name='image',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='gametable',
            name='server_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.realtimeserver'),
        ),
    ]
