# Generated by Django 3.1 on 2021-03-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20210315_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeserver',
            name='max_rooms',
            field=models.IntegerField(default=50),
        ),
    ]
