# Generated by Django 3.1 on 2021-06-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_realtimeserver_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametabletype',
            name='extra_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gametabletype',
            name='extra_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gametabletype',
            name='extra_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
