# Generated by Django 3.1 on 2021-06-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='game_table',
        ),
        migrations.AddField(
            model_name='transaction',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='misc.round'),
        ),
    ]
