# Generated by Django 3.1 on 2021-07-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_auto_20210614_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyGameMakerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Third Party Game Maker',
            },
        ),
        migrations.CreateModel(
            name='OrderID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=250)),
                ('game_maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_maker_order_id', to='misc.thirdpartygamemakermodel')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_order_id', to='misc.transaction')),
            ],
            options={
                'verbose_name': 'Order ID',
            },
        ),
    ]
