# Generated by Django 3.1 on 2021-07-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_orderid_thirdpartygamemakermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderid',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
