# Generated by Django 3.1 on 2021-07-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_orderid_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametable',
            name='game_table_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.gametabletype'),
        ),
    ]
