# Generated by Django 3.1 on 2021-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0010_auto_20210708_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_ref_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
