# Generated by Django 3.1 on 2021-09-09 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('misc', '0014_auto_20210908_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_receiver', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_sender', to='accounts.user'),
            preserve_default=False,
        ),
    ]
