# Generated by Django 3.1 on 2021-09-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_auto_20210909_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
