# Generated by Django 3.1 on 2021-09-26 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0024_gametabletype_max_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameservertransaction',
            name='receiver_ref_code',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_ref_code',
        ),
    ]
