# Generated by Django 3.1 on 2021-09-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0026_auto_20210926_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameServerTransaction',
        ),
    ]
