# Generated by Django 3.1 on 2021-09-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0027_delete_gameservertransaction'),
        ('misc', '0025_gametabletype_reference_note'),
    ]

    operations = [
    ]
