# Generated by Django 3.1 on 2021-09-30 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0028_merge_20210929_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='game_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.gametable'),
        ),
    ]
