# Generated by Django 3.1 on 2021-10-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0030_auto_20211002_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametabletype',
            name='max_currency',
            field=models.BigIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='gametabletype',
            name='min_currency',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='reward',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
